version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9000:9000"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8085:8080"

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"